# Author: baichen318@gmail.com


# chipyard research root path specifications
# make sure chipyar-research is at the 'rl' branch
# and it is an absolute path
chipyard-research-root: /Volumes/Research/repo/chipyard-research/


# gem5 research root path specifications
# it is an absolute path
gem5-research-root: /Volumes/Research/repo/gem5-repo/1


# design specifications
# 1-wide 4-fetch SonicBOOM
# 1-wide 8-fetch SonicBOOM
# 2-wide 4-fetch SonicBOOM
# 2-wide 8-fetch SonicBOOM
# 3-wide 4-fetch SonicBOOM
# 3-wide 8-fetch SonicBOOM
# 4-wide 4-fetch SonicBOOM
# 4-wide 8-fetch SonicBOOM
# 5-wide SonicBOOM
design: "1-wide 4-fetch SonicBOOM"


# benchmarks specifications
benchmarks:
  - median
  - towers
  - vvadd
  - multiply


# dataset specifications
dataset: data/boom/dataset.txt


# working mode specifications
# train | explore
mode: explore


# RL model root path specifications
rl-model: /Volumes/Research/repo/rl-explorer/logs/train-1-wide-4-fetch-SonicBOOM-baichen-192.168.0.104-2022-09-25-00-40/models/train-1-wide-4-fetch-SonicBOOM-baichen-192.168.0.104-2022-09-25-00-40.pt


# PPA models specifications
ppa-model: tools/models


# PPA preference scaling
ppa-preference:
  - 5
  - 1
  - 1


# the number of processes specifications
num-parallel: 1


# maximal sequence specifications
max-sequence: 1000000


# done condition: after `terminate-step`, the agent cannot explore a better design
terminate-step: 10


# the batch size for training specifications
sample-size: 8


# GPU utilization specifications
use-cuda: false


# the number of n-step evaluation specifications
num-step: 5


# softmax temperature specifications to encourage exploration
temperature: 10


# learning rate specifications
learning-rate: 0.001


# reward discount specifications
gamma: 0.99


# coefficient of generalized advantage estimator (GAE)
lambda: 0.95


# coefficient specifications between two critical loss components
beta: 0.5


# entropy coefficient specifications
alpha: 1


# clip gradient normalization
clip-grad-norm: 0.5


# the episode specifications begin to apply the envelope operator
episode-when-apply-envelope-operator: 1000


# the episode specifications to update the critic
update-critic-episode: 100


# output path specifications
output-path: logs
