# Author: baichen318@gmail.com


### algorithm settings
algo:
  # design specifications
  # small-SonicBOOM
  # medium-SonicBOOM
  # large-SonicBOOM
  # mega-SonicBOOM
  # giga-SonicBOOM
  design: "small-SonicBOOM"
  # the number of processes specifications
  num-parallel: 1
  # maximal episode specifications
  max-episode: 1000000
  # GPU utilization specifications
  use-cuda: false
  # output root specifications
  output-root: logs
  # working mode specifications
  # train | test
  mode: test
  random-seed: 42
  train:
    # the batch size for training specifications
    sample-size: 8
    # the number of n-step evaluation specifications
    num-step: 9
    # softmax temperature specifications to encourage exploration
    temperature: 10
    # learning rate specifications
    learning-rate: 0.001
    # reward discount specifications
    gamma: 0.99
    # coefficient of generalized advantage estimator (GAE)
    lambda: 0.95
    # coefficient specifications between two critical loss components
    beta: 0.5
    # entropy coefficient specifications
    alpha: 1
    # clip gradient normalization
    clip-grad-norm: 0.5
    # the episode specifications begin to apply the envelope operator
    episode-when-apply-envelope-operator: 1000
    # the episode specifications to update the critic
    update-critic-episode: 100
  test:
    # search round
    max-search-round: 100
    # PPA preference scaling
    ppa-preference:
      - 1
      - 1
      - 1
    # RL model specifications
    rl-model: /Volumes/Research/repo/rl-explorer/main/logs/train-large-SonicBOOM-cbai-hpc3.cse.cuhk.edu.hk-2023-05-05-15-50/models/log-2023-05-05-15-50.pt


### environment settings
env:
  ## VLSI flow settings
  vlsi:
    # chipyard research root path specifications
    # make sure chipyar-research is at the 'rl' branch
    # and it is an absolute path
    chipyard-research-root: /Volumes/Research/repo/chipyard-research/
  ## simulation settings
  sim:
    # gem5 research pool root path specifications
    # it is an absolute path
    gem5-research-root: /Volumes/Research/repo/gem5-repo/
    # an idx is set if a user specifies a specific gem5 repo.
    idx: 1
  ## calibration settings
  calib:
    # dataset specifications
    dataset: /Volumes/Research/repo/rl-explorer/data/boom/v3/boom.txt
    # simulation dataset specifications
    calib-dataset: /Volumes/Research/repo/rl-explorer/data/boom/v3/dataset.txt
    # PPA models specifications
    ppa-model: /Volumes/Research/repo/rl-explorer/tools/models/boom
  ## benchmarks specifications
  benchmarks:
    - towers
    - vvadd
    - spmv
    # - median
    # - multiply
