# Author: baichen318@gmail.com

# Total constraints:
#   1. isPow2(fetchWidth)
#   2. decodeWidth <= fetchWidth
#   3. icacheParams.nSets <= 64
#   4. numIntPhysRegisters >= (32 + decodeWidth)
#   5. numFpPhysRegisters >= (32 + decodeWidth)
#   6. maxBrCount >= 2
#   7. numRobEntries % decodeWidth == 0
#   8. (numLdqEntries - 1) > decodeWidth
#   9. (numStqEntries - 1) > decodeWidth
#   10. numFetchBufferEntries > fetchWidth
#   11. numFetchBufferEntries % decodeWidth == 0
#   12. fetchWidth = 4, icacheParams.fetchBytes = 2
#       fetchWidth = 8, icacheParams.fetchBytes = 4
#   13. numIntPhysRegisters == numFpPhysRegisters
#   14. numLdqEntries == numStqEntries
#   15. mem_issueWidth == fp_issueWidth

# Merged constraints (under this design space):
#   1. decodeWidth <= fetchWidth
#   2. numRobEntries % decodeWidth == 0
#   3. numFetchBufferEntries > fetchWidth &&
#      numFetchBufferEntries % decodeWidth == 0
#   4. fetchWidth = 4, ICacheParams_fetchBytes = 2
#      fetchWidth = 8, ICacheParams_fetchBytes = 4
#   5. numIntPhysRegisters == numFpPhysRegisters
#   6. numLdqEntries == numStqEntries
#   7. mem_issueWidth == fp_issueWidth

# Design space
basic-component:
  registers: [
      # numIntPhysRegisters numFpPhysRegisters
      [52, 48],
      [80, 64],
      [100, 96],
      [128, 128],
      [96, 64],
      [40, 40],
      [64, 60],
      [50, 46],
      [48, 44],
      [72, 68],
      [90, 86],
      [132, 132],
      [46, 42]
  ]
  issue-unit: [
      # IQT_MEM IQT_INT IQT_FP
      [8, 8, 8],
      [12, 20, 16],
      [16, 32, 24],
      [24, 40, 32],
      [10, 14, 12],
      [14, 26, 20],
      [20, 36, 28],
      [4, 4, 4],
      [6, 6, 6],
      [12, 28, 20],
      [14, 30, 22],
      [26, 42, 34]
  ]
  dcache: [
      # nMSHRs, nTLBWays
      [2, 8],
      [4, 16],
      [8, 32],
      [16, 48],
      [4, 8]
  ]
  lsu: [
      # numLdqEntries numStqEntries
      [8, 8],
      [16, 16],
      [24, 24],
      [32, 32],
      [40, 40],
      [20, 20],
      [6, 6],
      [30, 30],
      [34, 34],
      [42, 42]
  ]
  ifu-buffers: [
    # numFetchBufferEntries ftq.nEntries
    [8, 16],
    [16, 32],
    [24, 32],
    [32, 40],
    [40, 32],
    [30, 30],
    [45, 40],
    [4, 8],
    [6, 14],
    [14, 30],
    [30, 38],
    [36, 42],
    [35, 40],
    [32, 36]
  ]

# Design space
design-space:
  bpd:
    start: 0
    end: 2
    stride: 1
  fetchWidth:
    candidates: [4, 8]
  ifu-buffers:
    start: 0
    end: 13
    stride: 1
  maxBrCount:
    start: 6
    end: 22
    stride: 2
  decodeWidth:
    start: 1
    end: 5
    stride: 1
  numRobEntries:
    candidates: [30, 32, 36, 52, 64, 80, 84, 92, 96, 100, 105, 110, 118, 120, 128, 130, 134]
  registers:
    start: 0
    end: 12
    stride: 1
  issueEntries:
    start: 0
    end: 11
    stride: 1
  lsuEntries:
    start: 0
    end: 9
    stride: 1
  dcache:
    start: 0
    end: 4
    stride: 1

# Flow: initialize | search
# search includes data collection
# run VLSI flow manually!
flow: search

# Choose random | cbted
initialize-method: random

# ClustringBootstrapTED:
Nrted: 59
mu: 0.1
sig: 0.1
batch: 5

# Size
initialize-size: 200

# Record samples
initialize-output-path: data/sample

# Index for the first config.
idx: 1

# Collect area & Latency
vlsi-build-path: /research/dept8/gds/cbai/research/chipyard/vlsi/build

# Output path for latency
latency-output-path: data/latency.csv

# Output path for area
area-output-path: data/area.csv

# Collect power
pt-pwr-path: /research/dept8/gds/cbai/research/synopsys-flow/build/pt-pwr/

# Output path for power
power-output-path: data/power.csv

# Config. name
config-name:
  - chipyard.TestHarness.BOOMConfig1Config-ChipTop
  - chipyard.TestHarness.BOOMConfig2Config-ChipTop
  - chipyard.TestHarness.BOOMConfig3Config-ChipTop

# Output path for final training set
dataset-output-path: ../../data/boom/dataset-v1.txt

# Learning rate for `dnn-gp`
learning-rate: 0.001

# Optimizer for `dnn-gp` Adam | SGD
optimizer: Adam

# Max iteration for `dnn-gp`
max-epoch: 100

# Max iteration for Bayesian Optimization
max-bo-steps: 9

# MLP output dimension
mlp-output-dim: 6

# Number for clusters
cluster: 5

# Output path for models
model-output-path: model/dnn.mdl

# Output path for results
rpt-output-path: rpts/boom-explorer.rpt

# Output path for fig.
fig-output-path: data/boom-explorer.pdf

# Flag for `vis-crted`
vis-crted: False

# MOA3C YML interface
seed: 2021
# benchmarks
benchmarks:
  - median
  # - mt-vvadd
  # - mt-matmul
  - towers
  # - qsort
  # - rsort
  - vvadd
  - multiply
  # - dhrystone
  # - spmv

# design: boom | rocket | cva6
design: boom