# Author: baichen318@gmail.com


# chipyard research root path specifications
# make sure chipyar-research is at the 'rl' branch
# and it is an absolute path
chipyard-research-root: /Volumes/Research/repo/chipyard-research/


# gem5 research root path specifications
# it is an absolute path
gem5-research-root: /Volumes/Research/repo/gem5-repo


# design specifications
# 1-wide 4-fetch SonicBOOM
# 1-wide 8-fetch SonicBOOM
# 2-wide 4-fetch SonicBOOM
# 2-wide 8-fetch SonicBOOM
# 3-wide 4-fetch SonicBOOM
# 3-wide 8-fetch SonicBOOM
# 4-wide 4-fetch SonicBOOM
# 4-wide 8-fetch SonicBOOM
# 5-wide SonicBOOM
design: "1-wide 4-fetch SonicBOOM"


# benchmarks specifications
benchmarks:
  - median
  - towers
  - vvadd
  - multiply


# working mode specifications
# train | explore
mode: train


# PPA models specifications
ppa-model: tools/calib-models


# the number of processes specifications
num-parallel: 1


# maximal episode specifications
max-episode: 10000


# maximal step specifications
max-step-per-episode: 1000


# early stopping specifications in one episode
early-stopping-per-episode: 10


# the batch size for training specifications
sample-size: 8


# GPU utilization specifications
use-cuda: false


# the number of n-step evaluation specifications
num-step: 5


# softmax temperature specifications to encourage exploration
temperature: 10


# learning rate specifications
learning-rate: 0.001


# reward discount specifications
gamma: 0.99


# coefficient of generalized advantage estimator (GAE)
lambda: 0.95


# coefficient specifications between two critical loss components
beta: 0.5


# entropy coefficient specifications
alpha: 0.02


# clip gradient normalization
clip-grad-norm: 0.5


# the step specifications begin to apply the envelope operator
apply-envelope-operator-start: 1000


# the step specifications to update the critic
update-critic-step: 1000


# output path specifications
output-path: logs
