# Author: baichen318@gmail.com

design-space:
  fetchWidth:
    candidates: [4, 8]
  decodeWidth:
    start: 1
    end: 5
    stride: 1
  numFetchBufferEntries:
    start: 8
    end: 40
    stride: 8
  numRobEntries:
    start: 16
    end: 144
    stride: 8
  numRasEntries:
    start: 8
    end: 32
    stride: 8
  numIntPhysRegisters:
    start: 36
    end: 140
    stride: 4
  numFpPhysRegisters:
    start: 36
    end: 140
    stride: 4
  numLdqEntries:
    start: 4
    end: 36
    stride: 2
  numStqEntries:
    start: 4
    end: 36
    stride: 2
  maxBrCount:
    start: 6
    end: 22
    stride: 2
  mem_issueWidth:
    candidates: [1, 2]
  int_issueWidth:
    start: 1
    end: 5
    stride: 1
  fp_issueWidth:
    candidates: [1, 2]
  DCacheParams_nWays:
    candidates: [2, 4, 8]
  DCacheParams_nMSHRs:
    candidates: [2, 4, 8]
  DCacheParams_nTLBEntries:
    candidates: [8, 16, 32]
  ICacheParams_nWays:
    candidates: [2, 4, 8]
  ICacheParams_nTLBEntries:
    candidates: [8, 16, 32]
  ICacheParams_fetchBytes:
    candidates: [2, 4]

iteration: 5
report-output-path: results/result.rpt
model-output-path: models
