# Author: baichen318@gmail.com

# `numIntPhysRegisters` = `numFpPhysRegisters`
# `numLdqEntries` = `numStqEntries`
# `mem_issueWidth` = `fp_issueWidth`

design-space:
  fetchWidth:
    candidates: [4, 8]
  decodeWidth:
    start: 1
    end: 5
    stride: 1
  numFetchBufferEntries:
    candidates: [8, 16, 24, 32, 35, 40]
  numRobEntries:
    candidates: [32, 64, 96, 128, 130]
  numRasEntries:
    candidates: [16, 24, 32]
  numIntPhysRegisters:
    candidates: [48, 64, 80, 96, 112]
  numFpPhysRegisters:
    candidates: [48, 64, 80, 96, 112]
  numLdqEntries:
    candidates: [8, 16, 24, 32]
  numStqEntries:
    candidates: [8, 16, 24, 32]
  maxBrCount:
    candidates: [8, 12, 16, 20]
  mem_issueWidth:
    candidates: [1, 2]
  int_issueWidth:
    start: 1
    end: 5
    stride: 1
  fp_issueWidth:
    candidates: [1, 2]
  DCacheParams_nWays:
    candidates: [2, 4, 8]
  DCacheParams_nMSHRs:
    candidates: [2, 4, 8]
  DCacheParams_nTLBEntries:
    candidates: [8, 16, 32]
  ICacheParams_nWays:
    candidates: [2, 4, 8]
  ICacheParams_nTLBEntries:
    candidates: [8, 16, 32]
  ICacheParams_fetchBytes:
    candidates: [2, 4]

iteration: 5
report-output-path: results/result.rpt
model-output-path: models
parallel: False
# Currently only support `random`
sample-method: random
sample-size: 200