# Author: baichen318@gmail.com

## Parse data

# original data
feature-path: data/sample.txt
power-path: data/sample-power.csv
latency-path: data/sample-latency.csv
area-path: data/sample-area.csv
# power | latency | area | dataset
mode: dataset
# output data
output-path: data/init-dataset.csv
