
# Author: baichen318@gmail.com

# config-name:
#   - GigaBoomProConfig
#   - GigaBoomConfig
#   - GigaBoomSEConfig
#   - MegaBoomProConfig
#   - MegaBoomConfig
#   - MegaBoomSEConfig
#   - LargeBoomProConfig
#   - LargeBoomConfig
#   - LargeBoomSEConfig
#   - MediumBoomProConfig
#   - MediumBoomConfig
#   - MediumBoomSEConfig
#   - SmallBoomProConfig
#   - SmallBoomConfig
#   - SmallBoomSEConfig

# benchmark-name:
#   - fft.riscv
#   - h264_dec.riscv
#   - mm.riscv
#   - mt-matmul.riscv
#   - mt-vvadd.riscv
#   - qsort.riscv
#   - spmv.riscv
#   - whetstone.riscv

dataset-path: data/init-dataset.csv
# lr | lasso | ridge | svr | lsvr | xgb | rf | ab | gb | bg
model: lr
# train | test
mode: train
output-path: models/lr.mdl
# output-path: data/init-model.csv
