# Author: baichen318@gmail.com

## Parse data

# original data
data-path: /uac/gds/cbai/cbai/research/synopsys-flow/build/pt-pwr/
# power | latency | area
mode: power
# output data
output-path: data/boom-tile.csv
# configuration name
config-name:
  - GigaBoomProConfig-benchmarks
  - GigaBoomConfig-benchmarks
  - GigaBoomSEConfig-benchmarks
  - MegaBoomProConfig-benchmarks
  - MegaBoomConfig-benchmarks
  - MegaBoomSEConfig-benchmarks
  - LargeBoomProConfig-benchmarks
  - LargeBoomConfig-benchmarks
  - LargeBoomSEConfig-benchmarks
  - MediumBoomProConfig-benchmarks
  - MediumBoomConfig-benchmarks
  - MediumBoomSEConfig-benchmarks
  - SmallBoomProConfig-benchmarks
  - SmallBoomConfig-benchmarks
  - SmallBoomSEConfig-benchmarks

