# Author: baichen318@gmail.com

# Constraint
# None

basic-component:
  btb: [
    # nRAS BTBParams.nEntries BHTParams.nEntries
    # denote no btb
    [0, 0, 0],
    [6, 28, 512],
    [3, 14, 256],
    [12, 56, 512],
    [8, 32, 512]
  ]
  icache: [
    # nWays nTLBWays
    [4, 32],
    [1, 4],
    [2, 4],
    [2, 16],
    [2, 32],
    [1, 16]
  ]
  mulDiv: [
    # mulUnroll numEarlyOut divEarlyOut
    [8, 1, 1]
    [1, 0, 0]
    [8, 0, 0]
  ]
  dcache: [
    # nWays nTLBWays
    [4, 32],
    [1, 4],
    [2, 4],
    [2, 16],
    [2, 32],
    [1, 16]
  ]

# Design space
design-space:
  btb:
    start: 0
    end: 4
    stride: 1
  icache:
    start: 0
    end: 5
    stride: 1
  fpu:
    candidates: [0, 1]
  mulDiv:
    start: 0
    end: 2
    stride: 1
  useVM:
    candidates: [0, 1]
  dcache:
    start: 0
    end: 5
    stride: 1

# benchmarks
benchmarks:
  - median
  - towers
  - mt-vvadd
  - mt-matmul
  # - qsort
  # - rsort
  # - vvadd
  # - multiply
  # - dhrystone
  # - spmv

# mode: generate-design | sim | generate-data | rl
mode: rl

# design: boom | rocket | cva6
design: rocket

# generate-design: for `sample_v2` in rl-explorer/dse/env/design_space.py
batch: 32

# generate-design: design-output-path
design-output-path: data/test/design.txt

# sim: idx
idx: 1

# generate-data: data-output-path
data-output-path: data/test/dataset.txt

# RL related
episode: 100
epsilon-start: 1
epsilon-end: 0.1
epsilon-decay: 0.05
capacity: 5000
update-target-policy: 5
total-step: 150
early-stopping: 100
batch-size: 16
gamma: 0.8
learning-rate: 0.001
log: logs/dqn-rocket
search-round: 500
debug: True
