# Author: baichen318@gmail.com

# Constraint
# None

basic-component:
  btb: [
    # nRAS BTBParams.nEntries BHTParams.nEntries
    # denote no btb
    [0, 0, 0],
    [6, 28, 512],
    [3, 14, 256],
    [12, 56, 1024],
    [8, 32, 512]
  ]
  icache: [
    # nWays nTLBWays
    [4, 32],
    [1, 4],
    [2, 4],
    [2, 16],
    [2, 32],
    [1, 16]
  ]
  mulDiv: [
    # mulUnroll numEarlyOut divEarlyOut
    [8, 1, 1],
    [1, 0, 0],
    [8, 0, 0],
  ]
  dcache: [
    # nSets nWays nTLBWays nMSHRs
    [64, 4, 32, 1],
    [64, 1, 4, 0],
    [32, 1, 4, 0],
    [64, 2, 4, 0],
    [64, 2, 16, 0],
    [64, 2, 32, 1],
    [64, 1, 16, 0],
    [64, 4, 32, 2],
    [64, 1, 4, 2],
    [32, 4, 32, 2]
  ]

# Design space
design-space:
  btb:
    start: 0
    end: 4
    stride: 1
  icache:
    start: 0
    end: 5
    stride: 1
  fpu:
    candidates: [0, 1]
  mulDiv:
    start: 0
    end: 2
    stride: 1
  useVM:
    candidates: [0, 1]
  dcache:
    start: 0
    end: 9
    stride: 1

# benchmarks
benchmarks:
  - median
  - towers
  # - mt-vvadd
  # - mt-matmul
  # - qsort
  # - rsort
  - vvadd
  - multiply
  # - dhrystone
  # - spmv

# mode: generate-design | generate-dataset | rl
mode: rl

# design: boom | rocket | cva6
design: rocket

batch: 1000

# generate-design: design-output-path
design-output-path: data/rocket/rocket-design.txt

# sim: idx
idx: 1

# generate-data: data-output-path
dataset-output-path: data/rocket/dataset-v1.txt

# PPA related
# performance model learning rate
ipc-model-lr: 0.001
# power model learning rate
power-model-lr: 0.001
# area model learning rate
area-model-lr: 0.001
# epochs to train PPA models.
ppa-epoch: 2000
# ppa model path
ppa-model: calib-models

# Vis. related
# port
port: 20123

# RL related
# metrics:
metrics:
  - ipc
  - power
  - area
# cuda enable
cuda: False
# random seed
seed: 2021
# no. of A3C agents
num-process: 1
# discount factor for rewards
gamma: 0.99
# hidden size
hidden-size:
  - 1000
  - 500
  - 50
# no. of TD steps
n-step-td: 5
# no. of environment steps to train
num-train-step: 1000
# max. of environment steps
num-env-step: 20
# value loss coefficient
value-loss-weight: 0.1
# entropy term coefficient
entropy-weight: 0.01
# learning rate
lr: 0.0007
# RMSprop optimizer epsilon
eps: 0.00001
# RMSprop optimizer apha
alpha: 0.99
# max. norm of gradients
max-grad-norm: 0.5
# save interval, one save per n updates
save-interval: 1
# eval interval, one eval per n updates
eval-interval: 500
# TODO: these flags need to be verified
batch-size: 16
# intial beta for evelope A3C
beta: 0.01
log: logs/a3c-rocket
debug: False
