# Author: baichen318@gmail.com

## Parse data

# original data
data-path: /research/d3/cbai/research/chipyard/vlsi/build
# power | latency | area
mode: latency
# output data
output-path: data/sample-latency.csv
# configuration name
config-name:
  - chipyard.TestHarness.BOOMConfig1Config-ChipTop
  - chipyard.TestHarness.BOOMConfig2Config-ChipTop
  - chipyard.TestHarness.BOOMConfig3Config-ChipTop
  - chipyard.TestHarness.BOOMConfig4Config-ChipTop
  - chipyard.TestHarness.BOOMConfig5Config-ChipTop
  - chipyard.TestHarness.BOOMConfig6Config-ChipTop
  - chipyard.TestHarness.BOOMConfig7Config-ChipTop
  - chipyard.TestHarness.BOOMConfig8Config-ChipTop
  - chipyard.TestHarness.BOOMConfig9Config-ChipTop
  - chipyard.TestHarness.BOOMConfig10Config-ChipTop
  - chipyard.TestHarness.BOOMConfig11Config-ChipTop
  - chipyard.TestHarness.BOOMConfig12Config-ChipTop
  - chipyard.TestHarness.BOOMConfig13Config-ChipTop
  - chipyard.TestHarness.BOOMConfig14Config-ChipTop
  - chipyard.TestHarness.BOOMConfig15Config-ChipTop
  - chipyard.TestHarness.BOOMConfig16Config-ChipTop
  - chipyard.TestHarness.BOOMConfig17Config-ChipTop
  - chipyard.TestHarness.BOOMConfig18Config-ChipTop
  - chipyard.TestHarness.BOOMConfig19Config-ChipTop
  - chipyard.TestHarness.BOOMConfig20Config-ChipTop
  - chipyard.TestHarness.BOOMConfig21Config-ChipTop
  - chipyard.TestHarness.BOOMConfig22Config-ChipTop
  - chipyard.TestHarness.BOOMConfig23Config-ChipTop
  - chipyard.TestHarness.BOOMConfig24Config-ChipTop
  - chipyard.TestHarness.BOOMConfig25Config-ChipTop
  - chipyard.TestHarness.BOOMConfig26Config-ChipTop
  - chipyard.TestHarness.BOOMConfig27Config-ChipTop
  - chipyard.TestHarness.BOOMConfig28Config-ChipTop
  - chipyard.TestHarness.BOOMConfig29Config-ChipTop
  - chipyard.TestHarness.BOOMConfig30Config-ChipTop
  - chipyard.TestHarness.BOOMConfig31Config-ChipTop
  - chipyard.TestHarness.BOOMConfig32Config-ChipTop
  - chipyard.TestHarness.BOOMConfig33Config-ChipTop
  - chipyard.TestHarness.BOOMConfig34Config-ChipTop
  - chipyard.TestHarness.BOOMConfig35Config-ChipTop
  - chipyard.TestHarness.BOOMConfig36Config-ChipTop
  - chipyard.TestHarness.BOOMConfig37Config-ChipTop
  - chipyard.TestHarness.BOOMConfig38Config-ChipTop
  - chipyard.TestHarness.BOOMConfig39Config-ChipTop
  - chipyard.TestHarness.BOOMConfig40Config-ChipTop
  - chipyard.TestHarness.BOOMConfig41Config-ChipTop
  - chipyard.TestHarness.BOOMConfig42Config-ChipTop
  - chipyard.TestHarness.BOOMConfig43Config-ChipTop
  - chipyard.TestHarness.BOOMConfig44Config-ChipTop
  - chipyard.TestHarness.BOOMConfig45Config-ChipTop
  - chipyard.TestHarness.BOOMConfig46Config-ChipTop
  - chipyard.TestHarness.BOOMConfig47Config-ChipTop
  - chipyard.TestHarness.BOOMConfig48Config-ChipTop
  - chipyard.TestHarness.BOOMConfig49Config-ChipTop
  - chipyard.TestHarness.BOOMConfig50Config-ChipTop
  - chipyard.TestHarness.BOOMConfig51Config-ChipTop
  - chipyard.TestHarness.BOOMConfig52Config-ChipTop
  - chipyard.TestHarness.BOOMConfig53Config-ChipTop
  - chipyard.TestHarness.BOOMConfig54Config-ChipTop
  - chipyard.TestHarness.BOOMConfig55Config-ChipTop
  - chipyard.TestHarness.BOOMConfig56Config-ChipTop
  - chipyard.TestHarness.BOOMConfig57Config-ChipTop
  - chipyard.TestHarness.BOOMConfig58Config-ChipTop
  - chipyard.TestHarness.BOOMConfig59Config-ChipTop
  - chipyard.TestHarness.BOOMConfig60Config-ChipTop
  - chipyard.TestHarness.BOOMConfig61Config-ChipTop
  - chipyard.TestHarness.BOOMConfig62Config-ChipTop
  - chipyard.TestHarness.BOOMConfig63Config-ChipTop
  - chipyard.TestHarness.BOOMConfig64Config-ChipTop
  - chipyard.TestHarness.BOOMConfig65Config-ChipTop
  - chipyard.TestHarness.BOOMConfig66Config-ChipTop
  - chipyard.TestHarness.BOOMConfig67Config-ChipTop
  - chipyard.TestHarness.BOOMConfig68Config-ChipTop
  - chipyard.TestHarness.BOOMConfig69Config-ChipTop
  - chipyard.TestHarness.BOOMConfig70Config-ChipTop
  - chipyard.TestHarness.BOOMConfig71Config-ChipTop
  - chipyard.TestHarness.BOOMConfig72Config-ChipTop
  - chipyard.TestHarness.BOOMConfig73Config-ChipTop
  - chipyard.TestHarness.BOOMConfig74Config-ChipTop
  - chipyard.TestHarness.BOOMConfig75Config-ChipTop
  - chipyard.TestHarness.BOOMConfig76Config-ChipTop
  - chipyard.TestHarness.BOOMConfig77Config-ChipTop
  - chipyard.TestHarness.BOOMConfig78Config-ChipTop
  - chipyard.TestHarness.BOOMConfig79Config-ChipTop
  - chipyard.TestHarness.BOOMConfig80Config-ChipTop
  - chipyard.TestHarness.BOOMConfig81Config-ChipTop
  - chipyard.TestHarness.BOOMConfig82Config-ChipTop
  - chipyard.TestHarness.BOOMConfig83Config-ChipTop
  - chipyard.TestHarness.BOOMConfig84Config-ChipTop
  - chipyard.TestHarness.BOOMConfig85Config-ChipTop
  - chipyard.TestHarness.BOOMConfig86Config-ChipTop
  - chipyard.TestHarness.BOOMConfig87Config-ChipTop
  - chipyard.TestHarness.BOOMConfig88Config-ChipTop
  - chipyard.TestHarness.BOOMConfig89Config-ChipTop
  - chipyard.TestHarness.BOOMConfig90Config-ChipTop
  - chipyard.TestHarness.BOOMConfig91Config-ChipTop
  - chipyard.TestHarness.BOOMConfig92Config-ChipTop
  - chipyard.TestHarness.BOOMConfig93Config-ChipTop
  - chipyard.TestHarness.BOOMConfig94Config-ChipTop
  - chipyard.TestHarness.BOOMConfig95Config-ChipTop
  - chipyard.TestHarness.BOOMConfig96Config-ChipTop
  - chipyard.TestHarness.BOOMConfig97Config-ChipTop
  - chipyard.TestHarness.BOOMConfig98Config-ChipTop
  - chipyard.TestHarness.BOOMConfig99Config-ChipTop
  - chipyard.TestHarness.BOOMConfig100Config-ChipTop
  - chipyard.TestHarness.BOOMConfig101Config-ChipTop
  - chipyard.TestHarness.BOOMConfig102Config-ChipTop
  - chipyard.TestHarness.BOOMConfig103Config-ChipTop
  - chipyard.TestHarness.BOOMConfig104Config-ChipTop
  - chipyard.TestHarness.BOOMConfig105Config-ChipTop
  - chipyard.TestHarness.BOOMConfig106Config-ChipTop
  - chipyard.TestHarness.BOOMConfig107Config-ChipTop
  - chipyard.TestHarness.BOOMConfig108Config-ChipTop
  - chipyard.TestHarness.BOOMConfig109Config-ChipTop
  - chipyard.TestHarness.BOOMConfig110Config-ChipTop
  - chipyard.TestHarness.BOOMConfig111Config-ChipTop
  - chipyard.TestHarness.BOOMConfig112Config-ChipTop
  - chipyard.TestHarness.BOOMConfig113Config-ChipTop
  - chipyard.TestHarness.BOOMConfig114Config-ChipTop
  - chipyard.TestHarness.BOOMConfig115Config-ChipTop
  - chipyard.TestHarness.BOOMConfig116Config-ChipTop
  - chipyard.TestHarness.BOOMConfig117Config-ChipTop
  - chipyard.TestHarness.BOOMConfig118Config-ChipTop
  - chipyard.TestHarness.BOOMConfig119Config-ChipTop
  - chipyard.TestHarness.BOOMConfig120Config-ChipTop
  - chipyard.TestHarness.BOOMConfig121Config-ChipTop
  - chipyard.TestHarness.BOOMConfig122Config-ChipTop
  - chipyard.TestHarness.BOOMConfig123Config-ChipTop
  - chipyard.TestHarness.BOOMConfig124Config-ChipTop
  - chipyard.TestHarness.BOOMConfig125Config-ChipTop
  - chipyard.TestHarness.BOOMConfig126Config-ChipTop
  - chipyard.TestHarness.BOOMConfig127Config-ChipTop
  - chipyard.TestHarness.BOOMConfig128Config-ChipTop
  - chipyard.TestHarness.BOOMConfig129Config-ChipTop
  - chipyard.TestHarness.BOOMConfig130Config-ChipTop
  - chipyard.TestHarness.BOOMConfig131Config-ChipTop
  - chipyard.TestHarness.BOOMConfig132Config-ChipTop
  - chipyard.TestHarness.BOOMConfig133Config-ChipTop
  - chipyard.TestHarness.BOOMConfig134Config-ChipTop
  - chipyard.TestHarness.BOOMConfig135Config-ChipTop
  - chipyard.TestHarness.BOOMConfig136Config-ChipTop
  - chipyard.TestHarness.BOOMConfig137Config-ChipTop
  - chipyard.TestHarness.BOOMConfig138Config-ChipTop
  - chipyard.TestHarness.BOOMConfig139Config-ChipTop
  - chipyard.TestHarness.BOOMConfig140Config-ChipTop
  - chipyard.TestHarness.BOOMConfig141Config-ChipTop
  - chipyard.TestHarness.BOOMConfig142Config-ChipTop
  - chipyard.TestHarness.BOOMConfig143Config-ChipTop
  - chipyard.TestHarness.BOOMConfig144Config-ChipTop
  - chipyard.TestHarness.BOOMConfig145Config-ChipTop
  - chipyard.TestHarness.BOOMConfig146Config-ChipTop
  - chipyard.TestHarness.BOOMConfig147Config-ChipTop
  - chipyard.TestHarness.BOOMConfig148Config-ChipTop
  - chipyard.TestHarness.BOOMConfig149Config-ChipTop
  - chipyard.TestHarness.BOOMConfig150Config-ChipTop
  - chipyard.TestHarness.BOOMConfig151Config-ChipTop
  - chipyard.TestHarness.BOOMConfig152Config-ChipTop
  - chipyard.TestHarness.BOOMConfig153Config-ChipTop
  - chipyard.TestHarness.BOOMConfig154Config-ChipTop
  - chipyard.TestHarness.BOOMConfig155Config-ChipTop
  - chipyard.TestHarness.BOOMConfig156Config-ChipTop
  - chipyard.TestHarness.BOOMConfig157Config-ChipTop
  - chipyard.TestHarness.BOOMConfig158Config-ChipTop
  - chipyard.TestHarness.BOOMConfig159Config-ChipTop
  - chipyard.TestHarness.BOOMConfig160Config-ChipTop
  - chipyard.TestHarness.BOOMConfig161Config-ChipTop
  - chipyard.TestHarness.BOOMConfig162Config-ChipTop
  - chipyard.TestHarness.BOOMConfig163Config-ChipTop
  - chipyard.TestHarness.BOOMConfig164Config-ChipTop
  - chipyard.TestHarness.BOOMConfig165Config-ChipTop
  - chipyard.TestHarness.BOOMConfig166Config-ChipTop
  - chipyard.TestHarness.BOOMConfig167Config-ChipTop
  - chipyard.TestHarness.BOOMConfig168Config-ChipTop
  - chipyard.TestHarness.BOOMConfig169Config-ChipTop
  - chipyard.TestHarness.BOOMConfig170Config-ChipTop
  - chipyard.TestHarness.BOOMConfig171Config-ChipTop
  - chipyard.TestHarness.BOOMConfig172Config-ChipTop
  - chipyard.TestHarness.BOOMConfig173Config-ChipTop
  - chipyard.TestHarness.BOOMConfig174Config-ChipTop
  - chipyard.TestHarness.BOOMConfig175Config-ChipTop
  - chipyard.TestHarness.BOOMConfig176Config-ChipTop
  - chipyard.TestHarness.BOOMConfig177Config-ChipTop
  - chipyard.TestHarness.BOOMConfig178Config-ChipTop
  - chipyard.TestHarness.BOOMConfig179Config-ChipTop
  - chipyard.TestHarness.BOOMConfig180Config-ChipTop
  - chipyard.TestHarness.BOOMConfig181Config-ChipTop
  - chipyard.TestHarness.BOOMConfig182Config-ChipTop
  - chipyard.TestHarness.BOOMConfig183Config-ChipTop
  - chipyard.TestHarness.BOOMConfig184Config-ChipTop
  - chipyard.TestHarness.BOOMConfig185Config-ChipTop
  - chipyard.TestHarness.BOOMConfig186Config-ChipTop
  - chipyard.TestHarness.BOOMConfig187Config-ChipTop
  - chipyard.TestHarness.BOOMConfig188Config-ChipTop
  - chipyard.TestHarness.BOOMConfig189Config-ChipTop
  - chipyard.TestHarness.BOOMConfig190Config-ChipTop
  - chipyard.TestHarness.BOOMConfig191Config-ChipTop
  - chipyard.TestHarness.BOOMConfig192Config-ChipTop
  - chipyard.TestHarness.BOOMConfig193Config-ChipTop
  - chipyard.TestHarness.BOOMConfig194Config-ChipTop
  - chipyard.TestHarness.BOOMConfig195Config-ChipTop
  - chipyard.TestHarness.BOOMConfig196Config-ChipTop
  - chipyard.TestHarness.BOOMConfig197Config-ChipTop
  - chipyard.TestHarness.BOOMConfig198Config-ChipTop
  - chipyard.TestHarness.BOOMConfig199Config-ChipTop
  - chipyard.TestHarness.BOOMConfig200Config-ChipTop
