# Author: baichen318@gmail.com

output-path: data/

config-name:
  - Config1
  - Config2
  - Config3
  - Config4
  - Config5
  - Config6
  - Config7
  - Config8
  - Config9
  - Config10
  - Config12
  - Config13
  - Config14
  - Config15
  - Config16
  - Config17
  - Config18
  - Config19
  - Config20
  - Config21
  - Config22
  - Config23
  - Config24
  - Config25
  - Config26
  - Config27
  - Config28
  - Config29
  - Config30
  - Config31
  - Config32
  - Config33
  - Config34
  - Config35
  - Config36
  - Config37
  - Config38
  - Config39
  - Config40
  - Config41
  - Config42
  - Config43
  - Config44
  - Config45
  - Config46
  - Config47
  - Config48
  - Config49
  - Config50
  - Config51
  - Config52
  - Config53
  - Config54
  - Config55
  - Config56
  - Config57
  - Config58
  - Config59
  - Config60
  - Config61
  - Config62
  - Config63
  - Config64
  - Config65
  - Config66
  - Config67
  - Config68
  - Config69
  - Config70
  - Config71
  - Config72
  - Config73
  - Config74
  - Config75
  - Config76
  - Config77
  - Config78
  - Config79
  - Config80
  - Config81
  - Config82
  - Config83
  - Config84
  - Config85
  - Config86
  - Config87
  - Config88
  - Config89
  - Config90
  - Config91
  - Config92
  - Config93
  - Config94
  - Config95
  - Config96
  - Config97
  - Config98
  - Config99
  - Config100
  - Config101
  - Config102
  - Config103
  - Config104
  - Config105
  - Config106
  - Config107
  - Config108
  - Config109
  - Config110
  - Config111
  - Config112
  - Config113
  - Config114
  - Config115
  - Config116
  - Config117
  - Config118
  - Config119
  - Config120
  - Config121
  - Config122
  - Config123
  - Config124
  - Config125
  - Config126
  - Config127
  - Config128
  - Config129
  - Config130
  - Config131
  - Config132
  - Config133
  - Config134
  - Config135
  - Config136
  - Config137
  - Config138
  - Config139
  - Config140
  - Config141
  - Config142
  - Config143
  - Config144
  - Config145
  - Config146
  - Config147
  - Config148
  - Config149
  - Config150
  - Config151
  - Config152
  - Config153
  - Config154
  - Config155
  - Config156
  - Config157
  - Config158
  - Config159
  - Config160
  - Config161
  - Config162
  - Config163
  - Config164
  - Config165
  - Config166
  - Config167
  - Config168
  - Config169
  - Config170
  - Config171
  - Config172
  - Config173
  - Config174
  - Config175
  - Config176
  - Config177
  - Config178
  - Config179
  - Config181
  - Config182
  - Config183
  - Config184
  - Config185
  - Config186
  - Config187
  - Config188
  - Config189
  - Config190
  - Config191
  - Config192
  - Config193
  - Config194
  - Config195
  - Config196
  - Config197
  - Config198
  - Config199
  - Config200
benchmark-name:
  - whetstone.riscv
