# Author: baichen318@gmail.com

## Parse data

# original data
data-path: /research/dept8/gds/cbai/research/synopsys-flow/build/pt-pwr/
# power | latency | area
mode: power
# output data
output-path: data/sample-power.csv
# configuration name
config-name:
  - Config1-benchmarks
  - Config2-benchmarks
  - Config3-benchmarks
  - Config4-benchmarks
  - Config5-benchmarks
  - Config6-benchmarks
  - Config7-benchmarks
  - Config8-benchmarks
  - Config9-benchmarks
  - Config10-benchmarks
  - Config12-benchmarks
  - Config13-benchmarks
  - Config14-benchmarks
  - Config15-benchmarks
  - Config16-benchmarks
  - Config17-benchmarks
  - Config18-benchmarks
  - Config19-benchmarks
  - Config20-benchmarks
  - Config21-benchmarks
  - Config22-benchmarks
  - Config23-benchmarks
  - Config24-benchmarks
  - Config25-benchmarks
  - Config26-benchmarks
  - Config27-benchmarks
  - Config28-benchmarks
  - Config29-benchmarks
  - Config30-benchmarks
  - Config31-benchmarks
  - Config32-benchmarks
  - Config33-benchmarks
  - Config34-benchmarks
  - Config35-benchmarks
  - Config36-benchmarks
  - Config37-benchmarks
  - Config38-benchmarks
  - Config39-benchmarks
  - Config40-benchmarks
  - Config41-benchmarks
  - Config42-benchmarks
  - Config43-benchmarks
  - Config44-benchmarks
  - Config45-benchmarks
  - Config46-benchmarks
  - Config47-benchmarks
  - Config48-benchmarks
  - Config49-benchmarks
  - Config50-benchmarks
  - Config51-benchmarks
  - Config52-benchmarks
  - Config53-benchmarks
  - Config54-benchmarks
  - Config55-benchmarks
  - Config56-benchmarks
  - Config57-benchmarks
  - Config58-benchmarks
  - Config59-benchmarks
  - Config60-benchmarks
  - Config61-benchmarks
  - Config62-benchmarks
  - Config63-benchmarks
  - Config64-benchmarks
  - Config65-benchmarks
  - Config66-benchmarks
  - Config67-benchmarks
  - Config68-benchmarks
  - Config69-benchmarks
  - Config70-benchmarks
  - Config71-benchmarks
  - Config72-benchmarks
  - Config73-benchmarks
  - Config74-benchmarks
  - Config75-benchmarks
  - Config76-benchmarks
  - Config77-benchmarks
  - Config78-benchmarks
  - Config79-benchmarks
  - Config80-benchmarks
  - Config81-benchmarks
  - Config82-benchmarks
  - Config83-benchmarks
  - Config84-benchmarks
  - Config85-benchmarks
  - Config86-benchmarks
  - Config87-benchmarks
  - Config88-benchmarks
  - Config89-benchmarks
  - Config90-benchmarks
  - Config91-benchmarks
  - Config92-benchmarks
  - Config93-benchmarks
  - Config94-benchmarks
  - Config95-benchmarks
  - Config96-benchmarks
  - Config97-benchmarks
  - Config98-benchmarks
  - Config99-benchmarks
  - Config100-benchmarks
  - Config101-benchmarks
  - Config102-benchmarks
  - Config103-benchmarks
  - Config104-benchmarks
  - Config105-benchmarks
  - Config106-benchmarks
  - Config107-benchmarks
  - Config108-benchmarks
  - Config109-benchmarks
  - Config110-benchmarks
  - Config111-benchmarks
  - Config112-benchmarks
  - Config113-benchmarks
  - Config114-benchmarks
  - Config115-benchmarks
  - Config116-benchmarks
  - Config117-benchmarks
  - Config118-benchmarks
  - Config119-benchmarks
  - Config120-benchmarks
  - Config121-benchmarks
  - Config122-benchmarks
  - Config123-benchmarks
  - Config124-benchmarks
  - Config125-benchmarks
  - Config126-benchmarks
  - Config127-benchmarks
  - Config128-benchmarks
  - Config129-benchmarks
  - Config130-benchmarks
  - Config131-benchmarks
  - Config132-benchmarks
  - Config133-benchmarks
  - Config134-benchmarks
  - Config135-benchmarks
  - Config136-benchmarks
  - Config137-benchmarks
  - Config138-benchmarks
  - Config139-benchmarks
  - Config140-benchmarks
  - Config141-benchmarks
  - Config142-benchmarks
  - Config143-benchmarks
  - Config144-benchmarks
  - Config145-benchmarks
  - Config146-benchmarks
  - Config147-benchmarks
  - Config148-benchmarks
  - Config149-benchmarks
  - Config150-benchmarks
  - Config151-benchmarks
  - Config152-benchmarks
  - Config153-benchmarks
  - Config154-benchmarks
  - Config155-benchmarks
  - Config156-benchmarks
  - Config157-benchmarks
  - Config158-benchmarks
  - Config159-benchmarks
  - Config160-benchmarks
  - Config161-benchmarks
  - Config162-benchmarks
  - Config163-benchmarks
  - Config164-benchmarks
  - Config165-benchmarks
  - Config166-benchmarks
  - Config167-benchmarks
  - Config168-benchmarks
  - Config169-benchmarks
  - Config170-benchmarks
  - Config171-benchmarks
  - Config172-benchmarks
  - Config173-benchmarks
  - Config174-benchmarks
  - Config175-benchmarks
  - Config176-benchmarks
  - Config177-benchmarks
  - Config178-benchmarks
  - Config179-benchmarks
  - Config181-benchmarks
  - Config182-benchmarks
  - Config183-benchmarks
  - Config184-benchmarks
  - Config185-benchmarks
  - Config186-benchmarks
  - Config187-benchmarks
  - Config188-benchmarks
  - Config189-benchmarks
  - Config190-benchmarks
  - Config191-benchmarks
  - Config192-benchmarks
  - Config193-benchmarks
  - Config194-benchmarks
  - Config195-benchmarks
  - Config196-benchmarks
  - Config197-benchmarks
  - Config198-benchmarks
  - Config199-benchmarks
  - Config200-benchmarks
