# Author: baichen318@gmail.com

output-path: data/

config-name:
  - GigaBoomProConfig 
  - GigaBoomConfig
  - GigaBoomSEConfig
  - MegaBoomProConfig
  - MegaBoomConfig
  - MegaBoomSEConfig
  - LargeBoomProConfig
  - LargeBoomConfig
  - LargeBoomSEConfig
  - MediumBoomProConfig
  - MediumBoomConfig
  - MediumBoomSEConfig
  - SmallBoomProConfig
  - SmallBoomConfig
  - SmallBoomSEConfig
benchmark-name:
  - h264_dec.riscv
# 2d | 3d
mode: 2d
