# Author: baichen318@gmail.com

output-path: data/

config-name:
  - GigaBoomProConfig 
  - GigaBoomConfig
  - GigaBoomSEConfig
  - MegaBoomProConfig
  - MegaBoomConfig
  - MegaBoomSEConfig
  - LargeBoomProConfig
  - LargeBoomConfig
  - LargeBoomSEConfig
  - MediumBoomProConfig
  - MediumBoomConfig
  - MediumBoomSEConfig
  - SmallBoomProConfig
  - SmallBoomConfig
  - SmallBoomSEConfig
benchmark-name:
  - h264_dec.riscv
# v2 | v3 | v4
mode: v4
v4-input: data/xgb.predict
