# Author: baichen318@gmail.com


# random seed
seed: 42


# randomized TED specification
Nrted: 5


# randomized TED specification
mu: 0.1


# randomized TED specification
sig: 0.1


# batch specification in randomized TED
batch: 10


# decoder clustering weight specification
decoder-threshold: 3


# learning rate specification
learning-rate: 0.001


# optimizer specification
optimizer: Adam


# optimization steps specification for DKL-GP
max-optimize-epoch: 100


# max iteration specification for BO
max-bo-steps: 8


# MLP output dimension specification
mlp-output-dim: 6


# number for clusters specification in MicroAL
cluster: 5


# cluster iteration specification in MicroAL
cluster-iteration: 10


# sampled design space size specification in BO
sample-design-space-size: 1000
